name: url_converter
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.11.2 <3.0.0"

dependencies:
  clipboard_manager: ^0.0.4
  dio: ^4.0.6
  flutter:
    sdk: flutter
  get: ^4.6.1
  http: ^0.13.4

flutter:
  uses-material-design: true
